#!/bin/bash

echo 'Pengaturan Weeman Untuk Diaktifkan Di Termux'
echo 'Santai Dan Rileks yah'
apt update
apt upgrade -y
apt install git python python2 curl proot figlet -y
cd $HOME 
git clone http://github.com/bohemianskode/weeman
cp -rf weeman $PREFIX/share
rm -rf weeman
cd $HOME 
wget https://raw.githubusercontent.com/HackZonE404/SetupWeeman/master/weeman
wget https://raw.githubusercontent.com/HackZonE404/SetupWeeman/master/uninstallweeman 
chmod +x *
cp -rf weeman $PREFIX/bin/
cp -rf uninstallweeman $PREFIX/bin
cd $HOME
rm -rf weeman
rm -rf uninstallweeman
echo 'Successfully Installed Weeman Please Subscribe My Channel HackZonE'
